
# 🧠 Human-Like Picker — Train Models
This notebook trains two models from your built dataset:
1) **Move-choice ranker** — pick the most human-like move among Stockfish top-20.
2) **Think-time regressor** — predict human think time (ms) for the chosen move.

**Input**: the parquet built by your Top-20 Fast pipeline, e.g. `data/candidates_top20_fast_parallel_10k.parquet` or the *all* version.

In [1]:
# Install deps (LightGBM for ranking + parquet reader)
%pip -q install pandas pyarrow lightgbm scikit-learn joblib

Note: you may need to restart the kernel to use updated packages.

In [2]:

import os, math, numpy as np, pandas as pd
from pathlib import Path

# Pick your dataset path here (adjust if you wrote the _all version)
DATA_PATH = Path("data/candidates_top20_fast_parallel_10k.parquet")
if not DATA_PATH.exists():
    alt = Path("data/candidates_top20_fast_parallel_10k_all.parquet")
    if alt.exists():
        DATA_PATH = alt

print("Using dataset:", DATA_PATH)
df = pd.read_parquet(DATA_PATH)
print(df.shape)
df.head()

Using dataset: data\candidates_top20_fast_parallel_10k.parquet
(5590508, 14)

,group_id,fen,side,uci,label_choice,human_move_uci,human_think_ms,in_top20,ply,cp,mate,depth,pv_len,cp_to_best
0,5850265614594899970:0,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,1,e2e4,0,d2d4,0.0,1,1,36,0,0,0,0
1,5850265614594899970:0,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,1,d2d4,1,d2d4,0.0,1,1,20,0,0,0,16
2,5850265614594899970:0,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,1,g1f3,0,d2d4,0.0,1,1,19,0,0,0,17
3,5850265614594899970:0,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,1,e2e3,0,d2d4,0.0,1,1,18,0,0,0,18
4,5850265614594899970:0,rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w ...,1,c2c4,0,d2d4,0.0,1,1,17,0,0,0,19


## Clean & Features
We avoid label leakage: **do not use** `label_choice`, `human_move_uci`, or `in_top20` as features.  
We keep numeric features and add a compact encoding from `uci`.

In [3]:

import re

# Basic numeric features available
BASE_FEATS = ["side", "cp", "mate", "depth", "pv_len", "cp_to_best", "ply"]

# Encode UCI to compact numeric fields: from_sq (0..63), to_sq (0..63), promo (0..5)
FILES = {c:i for i,c in enumerate("abcdefgh")}
def sq_to_idx(sq):
    # 'a1'->0, 'b1'->1, ..., 'h8'->63
    if not isinstance(sq, str) or len(sq)<2: return -1
    file = FILES.get(sq[0], None)
    rank = int(sq[1]) - 1 if len(sq) > 1 and sq[1].isdigit() else None
    if file is None or rank is None or not (0<=rank<=7): return -1
    return rank*8 + file

PROMO = {"":0, "q":1, "r":2, "b":3, "n":4}
def uci_to_numeric(uci):
    uci = str(uci)
    from_sq = sq_to_idx(uci[0:2])
    to_sq   = sq_to_idx(uci[2:4])
    promo   = PROMO.get(uci[4:], 0) if len(uci) > 4 else 0
    return from_sq, to_sq, promo

fs, ts, ps = [], [], []
for u in df["uci"].astype(str).tolist():
    f, t, p = uci_to_numeric(u)
    fs.append(f); ts.append(t); ps.append(p)
df["uci_from"] = fs
df["uci_to"]   = ts
df["uci_promo"]= ps

FEATS = BASE_FEATS + ["uci_from","uci_to","uci_promo"]
df[FEATS + ["label_choice","in_top20","human_move_uci","human_think_ms"]].head(3)

,side,cp,mate,depth,pv_len,cp_to_best,ply,uci_from,uci_to,uci_promo,label_choice,in_top20,human_move_uci,human_think_ms
0,1,36,0,0,0,0,1,12,28,0,0,1,d2d4,0.0
1,1,20,0,0,0,16,1,11,27,0,1,1,d2d4,0.0
2,1,19,0,0,0,17,1,6,21,0,0,1,d2d4,0.0


## Train/Valid split by **group_id**
We split by groups so no leakage occurs across candidates of the same position.

In [4]:

from sklearn.model_selection import train_test_split

groups = df["group_id"].unique()
g_train, g_valid = train_test_split(groups, test_size=0.15, random_state=42, shuffle=True)

train = df[df["group_id"].isin(g_train)].copy()
valid = df[df["group_id"].isin(g_valid)].copy()

print("Train groups:", train["group_id"].nunique(), "rows:", len(train))
print("Valid groups:", valid["group_id"].nunique(), "rows:", len(valid))

Train groups: 243070 rows: 4751459
Valid groups: 42895 rows: 839049


## 1) Move-choice Ranker (LightGBM LambdaRank)
We train a ranking model to score candidate moves per group. At inference, pick the max-score move.

In [5]:
import lightgbm as lgb

# --- sort by group to align rows with group sizes ---
train_sorted = train.sort_values(["group_id"]).reset_index(drop=True)
valid_sorted = valid.sort_values(["group_id"]).reset_index(drop=True)

X_train = train_sorted[FEATS].fillna(0).astype(float)
y_train = train_sorted["label_choice"].astype(int)
X_valid = valid_sorted[FEATS].fillna(0).astype(float)
y_valid = valid_sorted["label_choice"].astype(int)

# group sizes must follow the same order as data rows
q_train = train_sorted.groupby("group_id").size().astype(int).values
q_valid = valid_sorted.groupby("group_id").size().astype(int).values

lgb_train = lgb.Dataset(X_train, label=y_train, group=q_train, params={"feature_pre_filter": False},)
lgb_valid = lgb.Dataset(X_valid, label=y_valid, group=q_valid, reference=lgb_train)

params = dict(
    objective="lambdarank",
    metric="ndcg",
    ndcg_eval_at=[1],
    boosting_type="gbdt",
    num_leaves=63,
    learning_rate=0.05,
    min_data_in_leaf=50,
    feature_fraction=0.9,
    bagging_fraction=0.8,
    bagging_freq=1,
    max_depth=-1,
    verbose=-1,
)

ranker = lgb.train(
    params,
    lgb_train,
    valid_sets=[lgb_train, lgb_valid],
    valid_names=["train","valid"],
    num_boost_round=200,
    callbacks=[
        lgb.early_stopping(stopping_rounds=30),
        lgb.log_evaluation(period=20),
    ],
)

# Validation: top-1 accuracy by group
valid_eval = valid_sorted.copy()
valid_eval["pred_score"] = ranker.predict(X_valid, num_iteration=ranker.best_iteration)

top_by_group = (valid_eval
                .sort_values(["group_id","pred_score"], ascending=[True, False])
                .groupby("group_id").head(1))
top1_acc = (top_by_group["label_choice"] == 1).mean()
print(f"Top-1 accuracy (by group): {top1_acc:.4f}")

# Coverage-conditioned accuracy (only groups where a human move exists in top-20)
valid_group_cov = valid_eval.groupby("group_id")["label_choice"].max().reset_index()
covered_groups = set(valid_group_cov[valid_group_cov["label_choice"]==1]["group_id"])
covered_acc = top_by_group[top_by_group["group_id"].isin(covered_groups)]
print(f"Top-1 accuracy on covered groups: {(covered_acc['label_choice']==1).mean():.4f}")

c:\Users\ppava\anaconda3\envs\chess-bot-env\Lib\site-packages\lightgbm\basic.py:2535: UserWarning: Overriding the parameters from Reference Dataset.
  _log_warning("Overriding the parameters from Reference Dataset.")

Training until validation scores don't improve for 30 rounds
[20]	train's ndcg@1: 0.400987	valid's ndcg@1: 0.398741
[40]	train's ndcg@1: 0.411881	valid's ndcg@1: 0.408136
[60]	train's ndcg@1: 0.417542	valid's ndcg@1: 0.414501
[80]	train's ndcg@1: 0.421973	valid's ndcg@1: 0.41886
[100]	train's ndcg@1: 0.425227	valid's ndcg@1: 0.422473
[120]	train's ndcg@1: 0.428115	valid's ndcg@1: 0.424572
[140]	train's ndcg@1: 0.430098	valid's ndcg@1: 0.426973
[160]	train's ndcg@1: 0.432114	valid's ndcg@1: 0.427789
[180]	train's ndcg@1: 0.433859	valid's ndcg@1: 0.429234
[200]	train's ndcg@1: 0.435385	valid's ndcg@1: 0.430143
Did not meet early stopping. Best iteration is:
[200]	train's ndcg@1: 0.435385	valid's ndcg@1: 0.430143
Top-1 accuracy (by group): 0.3962
Top-1 accuracy on covered groups: 0.4101

In [6]:
from lightgbm import LGBMRanker

ranker = LGBMRanker(
    objective="lambdarank",
    n_estimators=200,
    learning_rate=0.05,
    num_leaves=63,
    subsample=0.8,
    colsample_bytree=0.9,
    random_state=42,
)
ranker.fit(
    X_train, y_train,
    group=q_train,
    eval_set=[(X_valid, y_valid)],
    eval_group=[q_valid],
    eval_at=[1],
    callbacks=[lgb.early_stopping(60), lgb.log_evaluation(20)],
)

Training until validation scores don't improve for 60 rounds
[20]	valid_0's ndcg@1: 0.39944
[40]	valid_0's ndcg@1: 0.407833
[60]	valid_0's ndcg@1: 0.414943
[80]	valid_0's ndcg@1: 0.418604
[100]	valid_0's ndcg@1: 0.423219
[120]	valid_0's ndcg@1: 0.424921
[140]	valid_0's ndcg@1: 0.427229
[160]	valid_0's ndcg@1: 0.427975
[180]	valid_0's ndcg@1: 0.429211
[200]	valid_0's ndcg@1: 0.429444
Did not meet early stopping. Best iteration is:
[197]	valid_0's ndcg@1: 0.429584

LGBMRanker(colsample_bytree=0.9, learning_rate=0.05, n_estimators=200,
           num_leaves=63, objective='lambdarank', random_state=42,
           subsample=0.8)


## 2) Think-time Regressor (only on human-chosen rows)
We fit a regressor on the **positive** rows (where `label_choice==1` and think-time is present).  
We predict **log(1 + ms)** for stability; report MAE in ms on validation positives.

In [7]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import numpy as np

# Filter to positives with think time
train_pos = train[(train["label_choice"]==1) & (train["human_think_ms"].notnull())].copy()
valid_pos = valid[(valid["label_choice"]==1) & (valid["human_think_ms"].notnull())].copy()

def features_df(df_):
    return df_[FEATS].fillna(0).astype(float)

X_tr = features_df(train_pos)
y_tr = np.log1p(train_pos["human_think_ms"].astype(float))

X_va = features_df(valid_pos)
y_va = np.log1p(valid_pos["human_think_ms"].astype(float))

reg = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=3,
    n_jobs=-1,
    random_state=42
)
reg.fit(X_tr, y_tr)

pred_log = reg.predict(X_va)
pred_ms = np.expm1(pred_log).clip(min=0)

mae = mean_absolute_error(np.expm1(y_va), pred_ms)
print(f"Think-time MAE (ms) on validation positives: {mae:.1f} ms")

Think-time MAE (ms) on validation positives: 2422.8 ms


## Save models

In [8]:

import joblib, time
from pathlib import Path

out_dir = Path("models"); out_dir.mkdir(parents=True, exist_ok=True)
ts = time.strftime("%Y%m%d_%H%M%S")
rank_path = out_dir / f"move_ranker_lgb_{ts}.pkl"
time_path  = out_dir / f"time_regressor_rf_{ts}.pkl"

joblib.dump(ranker, rank_path)
joblib.dump(reg, time_path)

print("Saved:")
print(" -", rank_path)
print(" -", time_path)

Saved:
 - models\move_ranker_lgb_20251126_103155.pkl
 - models\time_regressor_rf_20251126_103155.pkl

In [9]:
import itertools
import random
import lightgbm as lgb

base_params = dict(
    objective="lambdarank",
    metric="ndcg",
    ndcg_eval_at=[1],
    boosting_type="gbdt",
    verbose=-1,
    feature_pre_filter=False,
)

search_space = {
    "num_leaves":        [31, 63, 127],
    "max_depth":         [-1, 6, 8, 10],
    "min_data_in_leaf":  [20, 50, 100, 200],
    "feature_fraction":  [0.6, 0.8, 1.0],
    "bagging_fraction":  [0.6, 0.8, 1.0],
    "bagging_freq":      [0, 1],
    "learning_rate":     [0.03, 0.05, 0.1],
    "lambda_l1":         [0.0, 0.1, 1.0],
    "lambda_l2":         [0.0, 0.1, 1.0],
}

def sample_params():
    params = base_params.copy()
    for k, v_list in search_space.items():
        params[k] = random.choice(v_list)
    return params

best_score = -1
best_params = None

for trial in range(30):  # e.g. 30 random trials
    params = sample_params()
    print(f"\n=== Trial {trial+1} params ===")
    print(params)

    model = lgb.train(
    params,
    lgb_train,
    valid_sets=[lgb_train, lgb_valid],
    valid_names=["train", "valid"],
    num_boost_round=1000,
    callbacks=[
        lgb.early_stopping(stopping_rounds=50),
        lgb.log_evaluation(period=50),
    ],
)

# For Booster from lgb.train -> use best_score (no underscore)
print(model.best_score)  # good to inspect once to see the keys

valid_score = model.best_score["valid"]["ndcg@1"]
print(f"Valid NDCG@1: {valid_score:.6f}")

=== Trial 1 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': -1, 'min_data_in_leaf': 200, 'feature_fraction': 0.6, 'bagging_fraction': 1.0, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 1.0, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.416851	valid's ndcg@1: 0.412915
[100]	train's ndcg@1: 0.424997	valid's ndcg@1: 0.420585
[150]	train's ndcg@1: 0.433217	valid's ndcg@1: 0.42611
[200]	train's ndcg@1: 0.438096	valid's ndcg@1: 0.428511
[250]	train's ndcg@1: 0.441667	valid's ndcg@1: 0.429934
[300]	train's ndcg@1: 0.445073	valid's ndcg@1: 0.430493
[350]	train's ndcg@1: 0.447406	valid's ndcg@1: 0.431076
[400]	train's ndcg@1: 0.450163	valid's ndcg@1: 0.430866
Early stopping, best iteration is:
[370]	train's ndcg@1: 0.448591	valid's ndcg@1: 0.431356

=== Trial 2 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 10, 'min_data_in_leaf': 100, 'feature_fraction': 1.0, 'bagging_fraction': 0.8, 'bagging_freq': 0, 'learning_rate': 0.05, 'lambda_l1': 0.1, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.414407	valid's ndcg@1: 0.410607
[100]	train's ndcg@1: 0.423627	valid's ndcg@1: 0.421541
[150]	train's ndcg@1: 0.428189	valid's ndcg@1: 0.424921
[200]	train's ndcg@1: 0.431653	valid's ndcg@1: 0.42695
[250]	train's ndcg@1: 0.434151	valid's ndcg@1: 0.428162
[300]	train's ndcg@1: 0.437203	valid's ndcg@1: 0.429304
[350]	train's ndcg@1: 0.439478	valid's ndcg@1: 0.429654
[400]	train's ndcg@1: 0.441626	valid's ndcg@1: 0.430003
[450]	train's ndcg@1: 0.44365	valid's ndcg@1: 0.42984
Early stopping, best iteration is:
[423]	train's ndcg@1: 0.442531	valid's ndcg@1: 0.430237

=== Trial 3 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 31, 'max_depth': -1, 'min_data_in_leaf': 200, 'feature_fraction': 0.8, 'bagging_fraction': 0.6, 'bagging_freq': 1, 'learning_rate': 0.03, 'lambda_l1': 1.0, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.396269	valid's ndcg@1: 0.393822
[100]	train's ndcg@1: 0.406471	valid's ndcg@1: 0.40338
[150]	train's ndcg@1: 0.413683	valid's ndcg@1: 0.411004
[200]	train's ndcg@1: 0.418295	valid's ndcg@1: 0.416179
[250]	train's ndcg@1: 0.421887	valid's ndcg@1: 0.419699
[300]	train's ndcg@1: 0.424725	valid's ndcg@1: 0.423289
[350]	train's ndcg@1: 0.426717	valid's ndcg@1: 0.425621
[400]	train's ndcg@1: 0.428535	valid's ndcg@1: 0.426996
[450]	train's ndcg@1: 0.430189	valid's ndcg@1: 0.428535
[500]	train's ndcg@1: 0.431505	valid's ndcg@1: 0.429304
[550]	train's ndcg@1: 0.432678	valid's ndcg@1: 0.429957
[600]	train's ndcg@1: 0.433867	valid's ndcg@1: 0.43061
[650]	train's ndcg@1: 0.434969	valid's ndcg@1: 0.431099
[700]	train's ndcg@1: 0.43606	valid's ndcg@1: 0.431869
[750]	train's ndcg@1: 0.437022	valid's ndcg@1: 0.432078
[800]	train's ndcg@1: 0.437833	valid's ndcg@1: 0.432615
[850]	train's ndcg@1: 0.438886	valid's ndcg@1: 0.433081
Early stopping, best iteration is:
[835]	train's ndcg@1: 0.43861	valid's ndcg@1: 0.433291

=== Trial 4 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 127, 'max_depth': 6, 'min_data_in_leaf': 200, 'feature_fraction': 0.6, 'bagging_fraction': 0.8, 'bagging_freq': 1, 'learning_rate': 0.03, 'lambda_l1': 0.0, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.397532	valid's ndcg@1: 0.394125
[100]	train's ndcg@1: 0.404007	valid's ndcg@1: 0.399534
[150]	train's ndcg@1: 0.411157	valid's ndcg@1: 0.406691
[200]	train's ndcg@1: 0.415605	valid's ndcg@1: 0.412123
[250]	train's ndcg@1: 0.419669	valid's ndcg@1: 0.415643
[300]	train's ndcg@1: 0.423248	valid's ndcg@1: 0.418743
[350]	train's ndcg@1: 0.425384	valid's ndcg@1: 0.420562
[400]	train's ndcg@1: 0.42726	valid's ndcg@1: 0.421448
[450]	train's ndcg@1: 0.429601	valid's ndcg@1: 0.422986
[500]	train's ndcg@1: 0.431452	valid's ndcg@1: 0.424735
[550]	train's ndcg@1: 0.432834	valid's ndcg@1: 0.425364
[600]	train's ndcg@1: 0.434142	valid's ndcg@1: 0.426763
[650]	train's ndcg@1: 0.435418	valid's ndcg@1: 0.427719
[700]	train's ndcg@1: 0.436331	valid's ndcg@1: 0.428628
[750]	train's ndcg@1: 0.437339	valid's ndcg@1: 0.429001
[800]	train's ndcg@1: 0.438516	valid's ndcg@1: 0.42977
[850]	train's ndcg@1: 0.439458	valid's ndcg@1: 0.429887
[900]	train's ndcg@1: 0.440223	valid's ndcg@1: 0.43054
[950]	train's ndcg@1: 0.441165	valid's ndcg@1: 0.430936
[1000]	train's ndcg@1: 0.442189	valid's ndcg@1: 0.431192
Did not meet early stopping. Best iteration is:
[990]	train's ndcg@1: 0.441955	valid's ndcg@1: 0.431426

=== Trial 5 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 31, 'max_depth': 6, 'min_data_in_leaf': 100, 'feature_fraction': 0.8, 'bagging_fraction': 1.0, 'bagging_freq': 0, 'learning_rate': 0.1, 'lambda_l1': 0.1, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.408775	valid's ndcg@1: 0.406411
[100]	train's ndcg@1: 0.419587	valid's ndcg@1: 0.417391
[150]	train's ndcg@1: 0.424684	valid's ndcg@1: 0.421891
[200]	train's ndcg@1: 0.428272	valid's ndcg@1: 0.424245
[250]	train's ndcg@1: 0.431053	valid's ndcg@1: 0.42653
[300]	train's ndcg@1: 0.433492	valid's ndcg@1: 0.428069
[350]	train's ndcg@1: 0.435253	valid's ndcg@1: 0.428884
[400]	train's ndcg@1: 0.43703	valid's ndcg@1: 0.429351
Early stopping, best iteration is:
[367]	train's ndcg@1: 0.435854	valid's ndcg@1: 0.429351

=== Trial 6 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 127, 'max_depth': 8, 'min_data_in_leaf': 200, 'feature_fraction': 1.0, 'bagging_fraction': 0.6, 'bagging_freq': 0, 'learning_rate': 0.03, 'lambda_l1': 1.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.409532	valid's ndcg@1: 0.404616
[100]	train's ndcg@1: 0.417151	valid's ndcg@1: 0.41126
[150]	train's ndcg@1: 0.42375	valid's ndcg@1: 0.417065
[200]	train's ndcg@1: 0.427737	valid's ndcg@1: 0.419909
[250]	train's ndcg@1: 0.431176	valid's ndcg@1: 0.421727
[300]	train's ndcg@1: 0.433871	valid's ndcg@1: 0.42294
[350]	train's ndcg@1: 0.435981	valid's ndcg@1: 0.423872
[400]	train's ndcg@1: 0.438207	valid's ndcg@1: 0.425085
Early stopping, best iteration is:
[380]	train's ndcg@1: 0.437269	valid's ndcg@1: 0.425224

=== Trial 7 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': -1, 'min_data_in_leaf': 50, 'feature_fraction': 0.6, 'bagging_fraction': 1.0, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 0.0, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.419101	valid's ndcg@1: 0.415316
[100]	train's ndcg@1: 0.430456	valid's ndcg@1: 0.424548
[150]	train's ndcg@1: 0.437158	valid's ndcg@1: 0.430307
[200]	train's ndcg@1: 0.44277	valid's ndcg@1: 0.431472
[250]	train's ndcg@1: 0.447213	valid's ndcg@1: 0.432545
[300]	train's ndcg@1: 0.450537	valid's ndcg@1: 0.432871
[350]	train's ndcg@1: 0.453754	valid's ndcg@1: 0.433617
[400]	train's ndcg@1: 0.456428	valid's ndcg@1: 0.43385
[450]	train's ndcg@1: 0.459732	valid's ndcg@1: 0.434293
Early stopping, best iteration is:
[444]	train's ndcg@1: 0.459349	valid's ndcg@1: 0.434689

=== Trial 8 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 31, 'max_depth': 6, 'min_data_in_leaf': 20, 'feature_fraction': 1.0, 'bagging_fraction': 1.0, 'bagging_freq': 0, 'learning_rate': 0.05, 'lambda_l1': 0.1, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.399934	valid's ndcg@1: 0.397086
[100]	train's ndcg@1: 0.412104	valid's ndcg@1: 0.409885
[150]	train's ndcg@1: 0.418225	valid's ndcg@1: 0.416459
[200]	train's ndcg@1: 0.421237	valid's ndcg@1: 0.418977
[250]	train's ndcg@1: 0.424075	valid's ndcg@1: 0.420678
[300]	train's ndcg@1: 0.426108	valid's ndcg@1: 0.422334
[350]	train's ndcg@1: 0.428194	valid's ndcg@1: 0.423709
[400]	train's ndcg@1: 0.429703	valid's ndcg@1: 0.425178
[450]	train's ndcg@1: 0.431061	valid's ndcg@1: 0.425154
Early stopping, best iteration is:
[412]	train's ndcg@1: 0.430012	valid's ndcg@1: 0.425318

=== Trial 9 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 8, 'min_data_in_leaf': 200, 'feature_fraction': 0.8, 'bagging_fraction': 0.8, 'bagging_freq': 1, 'learning_rate': 0.03, 'lambda_l1': 0.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.403336	valid's ndcg@1: 0.40042
[100]	train's ndcg@1: 0.413354	valid's ndcg@1: 0.409465
[150]	train's ndcg@1: 0.419612	valid's ndcg@1: 0.416249
[200]	train's ndcg@1: 0.423783	valid's ndcg@1: 0.420725
[250]	train's ndcg@1: 0.427198	valid's ndcg@1: 0.423336
[300]	train's ndcg@1: 0.430279	valid's ndcg@1: 0.425434
[350]	train's ndcg@1: 0.432756	valid's ndcg@1: 0.426973
[400]	train's ndcg@1: 0.434607	valid's ndcg@1: 0.428395
[450]	train's ndcg@1: 0.436882	valid's ndcg@1: 0.429537
[500]	train's ndcg@1: 0.438413	valid's ndcg@1: 0.430353
[550]	train's ndcg@1: 0.439956	valid's ndcg@1: 0.430866
[600]	train's ndcg@1: 0.441235	valid's ndcg@1: 0.431775
[650]	train's ndcg@1: 0.442539	valid's ndcg@1: 0.432055
Early stopping, best iteration is:
[616]	train's ndcg@1: 0.441605	valid's ndcg@1: 0.432311

=== Trial 10 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 10, 'min_data_in_leaf': 20, 'feature_fraction': 0.6, 'bagging_fraction': 1.0, 'bagging_freq': 0, 'learning_rate': 0.03, 'lambda_l1': 1.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.403032	valid's ndcg@1: 0.399767
[100]	train's ndcg@1: 0.411626	valid's ndcg@1: 0.408882
[150]	train's ndcg@1: 0.417481	valid's ndcg@1: 0.413102
[200]	train's ndcg@1: 0.420319	valid's ndcg@1: 0.416692
[250]	train's ndcg@1: 0.422216	valid's ndcg@1: 0.418184
[300]	train's ndcg@1: 0.423977	valid's ndcg@1: 0.419536
[350]	train's ndcg@1: 0.425264	valid's ndcg@1: 0.419489
[400]	train's ndcg@1: 0.426799	valid's ndcg@1: 0.420119
[450]	train's ndcg@1: 0.428272	valid's ndcg@1: 0.420958
[500]	train's ndcg@1: 0.429798	valid's ndcg@1: 0.421121
Early stopping, best iteration is:
[464]	train's ndcg@1: 0.428539	valid's ndcg@1: 0.421308

=== Trial 11 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 8, 'min_data_in_leaf': 20, 'feature_fraction': 1.0, 'bagging_fraction': 1.0, 'bagging_freq': 0, 'learning_rate': 0.1, 'lambda_l1': 0.0, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.422282	valid's ndcg@1: 0.420259
[100]	train's ndcg@1: 0.430987	valid's ndcg@1: 0.42611
[150]	train's ndcg@1: 0.437446	valid's ndcg@1: 0.428954
[200]	train's ndcg@1: 0.442313	valid's ndcg@1: 0.43075
[250]	train's ndcg@1: 0.446069	valid's ndcg@1: 0.431635
[300]	train's ndcg@1: 0.449652	valid's ndcg@1: 0.432172
[350]	train's ndcg@1: 0.452697	valid's ndcg@1: 0.431822
[400]	train's ndcg@1: 0.45542	valid's ndcg@1: 0.432498
Early stopping, best iteration is:
[386]	train's ndcg@1: 0.454754	valid's ndcg@1: 0.432638

=== Trial 12 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 10, 'min_data_in_leaf': 50, 'feature_fraction': 1.0, 'bagging_fraction': 1.0, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 1.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.41586	valid's ndcg@1: 0.411167
[100]	train's ndcg@1: 0.425602	valid's ndcg@1: 0.419653
[150]	train's ndcg@1: 0.431814	valid's ndcg@1: 0.422357
[200]	train's ndcg@1: 0.436031	valid's ndcg@1: 0.423616
[250]	train's ndcg@1: 0.440083	valid's ndcg@1: 0.42294
Early stopping, best iteration is:
[222]	train's ndcg@1: 0.437837	valid's ndcg@1: 0.423849

=== Trial 13 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 127, 'max_depth': 8, 'min_data_in_leaf': 20, 'feature_fraction': 1.0, 'bagging_fraction': 0.6, 'bagging_freq': 0, 'learning_rate': 0.1, 'lambda_l1': 0.1, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.426387	valid's ndcg@1: 0.419862
[100]	train's ndcg@1: 0.436574	valid's ndcg@1: 0.425085
[150]	train's ndcg@1: 0.443132	valid's ndcg@1: 0.427532
[200]	train's ndcg@1: 0.449155	valid's ndcg@1: 0.427742
Early stopping, best iteration is:
[181]	train's ndcg@1: 0.446949	valid's ndcg@1: 0.428138

=== Trial 14 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 127, 'max_depth': 10, 'min_data_in_leaf': 200, 'feature_fraction': 0.6, 'bagging_fraction': 0.6, 'bagging_freq': 0, 'learning_rate': 0.05, 'lambda_l1': 0.1, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.412515	valid's ndcg@1: 0.408556
[100]	train's ndcg@1: 0.423364	valid's ndcg@1: 0.416552
[150]	train's ndcg@1: 0.429337	valid's ndcg@1: 0.421844
[200]	train's ndcg@1: 0.435447	valid's ndcg@1: 0.425154
[250]	train's ndcg@1: 0.440058	valid's ndcg@1: 0.426903
[300]	train's ndcg@1: 0.443683	valid's ndcg@1: 0.427765
[350]	train's ndcg@1: 0.445987	valid's ndcg@1: 0.428698
[400]	train's ndcg@1: 0.448941	valid's ndcg@1: 0.428745
[450]	train's ndcg@1: 0.451586	valid's ndcg@1: 0.429677
Early stopping, best iteration is:
[446]	train's ndcg@1: 0.451409	valid's ndcg@1: 0.429864

=== Trial 15 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 6, 'min_data_in_leaf': 100, 'feature_fraction': 0.8, 'bagging_fraction': 0.6, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 0.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.414103	valid's ndcg@1: 0.409768
[100]	train's ndcg@1: 0.426383	valid's ndcg@1: 0.422427
[150]	train's ndcg@1: 0.431921	valid's ndcg@1: 0.425481
[200]	train's ndcg@1: 0.436055	valid's ndcg@1: 0.427835
[250]	train's ndcg@1: 0.439779	valid's ndcg@1: 0.43061
Early stopping, best iteration is:
[240]	train's ndcg@1: 0.439277	valid's ndcg@1: 0.430843

=== Trial 16 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': 8, 'min_data_in_leaf': 100, 'feature_fraction': 0.6, 'bagging_fraction': 0.8, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 1.0, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.416185	valid's ndcg@1: 0.412239
[100]	train's ndcg@1: 0.42821	valid's ndcg@1: 0.423313
[150]	train's ndcg@1: 0.435315	valid's ndcg@1: 0.428255
[200]	train's ndcg@1: 0.440153	valid's ndcg@1: 0.429817
[250]	train's ndcg@1: 0.444086	valid's ndcg@1: 0.4304
[300]	train's ndcg@1: 0.447324	valid's ndcg@1: 0.431426
[350]	train's ndcg@1: 0.450179	valid's ndcg@1: 0.432545
[400]	train's ndcg@1: 0.452894	valid's ndcg@1: 0.433477
[450]	train's ndcg@1: 0.455054	valid's ndcg@1: 0.433454
Early stopping, best iteration is:
[404]	train's ndcg@1: 0.453059	valid's ndcg@1: 0.433617

=== Trial 17 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 63, 'max_depth': -1, 'min_data_in_leaf': 20, 'feature_fraction': 1.0, 'bagging_fraction': 0.8, 'bagging_freq': 1, 'learning_rate': 0.03, 'lambda_l1': 0.0, 'lambda_l2': 0.1}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.407961	valid's ndcg@1: 0.405059
[100]	train's ndcg@1: 0.41876	valid's ndcg@1: 0.41464
[150]	train's ndcg@1: 0.424734	valid's ndcg@1: 0.421588
[200]	train's ndcg@1: 0.428897	valid's ndcg@1: 0.425341
[250]	train's ndcg@1: 0.431859	valid's ndcg@1: 0.428278
[300]	train's ndcg@1: 0.434422	valid's ndcg@1: 0.429491
[350]	train's ndcg@1: 0.436668	valid's ndcg@1: 0.43012
[400]	train's ndcg@1: 0.438623	valid's ndcg@1: 0.431123
[450]	train's ndcg@1: 0.44068	valid's ndcg@1: 0.430983
[500]	train's ndcg@1: 0.44265	valid's ndcg@1: 0.431472
[550]	train's ndcg@1: 0.444551	valid's ndcg@1: 0.431962
[600]	train's ndcg@1: 0.446291	valid's ndcg@1: 0.432172
Early stopping, best iteration is:
[584]	train's ndcg@1: 0.445629	valid's ndcg@1: 0.432475

=== Trial 18 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 31, 'max_depth': 10, 'min_data_in_leaf': 20, 'feature_fraction': 1.0, 'bagging_fraction': 1.0, 'bagging_freq': 0, 'learning_rate': 0.05, 'lambda_l1': 0.0, 'lambda_l2': 1.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.402353	valid's ndcg@1: 0.399347
[100]	train's ndcg@1: 0.417386	valid's ndcg@1: 0.415433
[150]	train's ndcg@1: 0.423014	valid's ndcg@1: 0.421844
[200]	train's ndcg@1: 0.426721	valid's ndcg@1: 0.424945
[250]	train's ndcg@1: 0.429473	valid's ndcg@1: 0.427253
[300]	train's ndcg@1: 0.431941	valid's ndcg@1: 0.429048
[350]	train's ndcg@1: 0.434007	valid's ndcg@1: 0.42984
[400]	train's ndcg@1: 0.435726	valid's ndcg@1: 0.43012
[450]	train's ndcg@1: 0.437294	valid's ndcg@1: 0.430819
[500]	train's ndcg@1: 0.438857	valid's ndcg@1: 0.431332
[550]	train's ndcg@1: 0.440001	valid's ndcg@1: 0.431659
[600]	train's ndcg@1: 0.441227	valid's ndcg@1: 0.432102
[650]	train's ndcg@1: 0.44235	valid's ndcg@1: 0.432311
[700]	train's ndcg@1: 0.443716	valid's ndcg@1: 0.432778
Early stopping, best iteration is:
[693]	train's ndcg@1: 0.443514	valid's ndcg@1: 0.432871

=== Trial 19 params ===
{'objective': 'lambdarank', 'metric': 'ndcg', 'ndcg_eval_at': [1], 'boosting_type': 'gbdt', 'verbose': -1, 'feature_pre_filter': False, 'num_leaves': 127, 'max_depth': 10, 'min_data_in_leaf': 200, 'feature_fraction': 0.6, 'bagging_fraction': 0.6, 'bagging_freq': 1, 'learning_rate': 0.1, 'lambda_l1': 0.0, 'lambda_l2': 0.0}
Training until validation scores don't improve for 50 rounds
[50]	train's ndcg@1: 0.423915	valid's ndcg@1: 0.418254
[100]	train's ndcg@1: 0.437676	valid's ndcg@1: 0.427019
[150]	train's ndcg@1: 0.446986	valid's ndcg@1: 0.42991
[200]	train's ndcg@1: 0.453507	valid's ndcg@1: 0.430866
[250]	train's ndcg@1: 0.458823	valid's ndcg@1: 0.43075
[300]	train's ndcg@1: 0.463591	valid's ndcg@1: 0.431099
Early stopping, best iteration is:
[265]	train's ndcg@1: 0.460106	valid's ndcg@1: 0.431612

=== Trial 20 params ===